# Generated by Django 5.1.3 on 2024-12-01 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encrypt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_inicial', models.CharField(max_length=32)),
                ('clave', models.CharField(max_length=32)),
                ('clave_inv_sep', models.CharField(max_length=64)),
                ('mensaje_cifrado_aes', models.CharField(max_length=100)),
                ('mensaje_cifrado_final', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
